### ISSUE TITLE
Alguns recursos que eu uso com frequemcia

### ISSUE THREAD

**Issue by lai32290** [jonathanslima/track-to-learn-english#11]
Canal YouTube
English with Lucy 
https://www.youtube.com/channel/UCz4tgANd4yy8Oe0iXCdSWfA

mmmEnglish
https://www.youtube.com/channel/UCrRiVfHqBIIvSgKmgnSY66g

App
- HiNative (uso para conferir se a sentença sound natural)
- HelloTalk (chat para language exchanges, contém função de correção de texto)

Sites
- Consulta de conjugação de verbo
http://conjugator.reverso.net/conjugation-english.html
- Ouvir pronúncia da palavra 
http://youglish.com/
- Treinar listening com música
https://lyricstraining.com/

**Comment by jonathanslima** [comment]
Wow muito bom o conteúdo, valeu por contribuir :)
