### ISSUE TITLE
Contribute Guide

### ISSUE THREAD

**Issue by woliveiras** [jonathanslima/track-to-learn-english#5]
Fala @jonathanslima,

Coloca um arquio no Repo chamado: CONTRIBUTE.md.

Deixa nele os guias sobre como contribuir aqui. :)

Essa issue pode ser usada para reunir as informações que vão ser adicionadas ao arquivo como:
- Padrões de escrita
- Ordem dos links (alfabética, pilha, etc)

**Comment by jonathanslima** [comment]
Ótima ideia @woliveiras vou arquitetar esse guia e coloco no repo

**Comment by woliveiras** [comment]
Show de bola

**Comment by Marcelosilva10** [comment]
Pessoal https://www.busuu.com
essa menina tbm ensina muito bem também.
https://www.youtube.com/channel/UCUtD2LXGx79oiFUwTGY_-6g

**Comment by jonathanslima** [comment]
Valeu @Marcelosilva10 vou incluir aqui
